apiVersion: v1
kind: ConfigMap
metadata:
  name: showcase-qic-frontend-nginx-config
  namespace: qapp-application
data:
  nginx.conf: |
    worker_processes  auto;

    error_log  /dev/stderr notice;
    pid        /tmp/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        client_max_body_size 0;
        limit_rate 0;
        limit_rate_after 0;
        sendfile_max_chunk 0;

        client_body_buffer_size 512k;
        client_header_buffer_size 64k;
        large_client_header_buffers 16 64k;

        proxy_temp_path /tmp/proxy_temp;
        client_body_temp_path /tmp/client_temp;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;

        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for" '
                          '"$server_name" '
                          '"$server_port" '
                          '"$request_length bytes" '
                          '"$request_time sec"';

        access_log /dev/stdout main;
        sendfile on;
        keepalive_timeout  65;

        server {
            listen 8080;
            server_name case-qic.quapp.store;
            location / {
                root   /usr/share/nginx/html;
                index  index.html;
                try_files $uri $uri/ /index.html;
            }
            location /q-image-compressor/ {
                rewrite ^/q-image-compressor/(.*)$ /api/q-image-compressor/$1 break;
                proxy_pass http://qapp-showcase-service-backend-svc.qapp-application.svc.cluster.local:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /q-classifier/ {
                rewrite ^/q-classifier/(.*)$ /api/q-classifier/$1 break;
                proxy_pass http://qapp-showcase-service-backend-svc.qapp-application.svc.cluster.local:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
        include /etc/nginx/conf.d/*.conf;
    }
